spring:
  datasource:
    url: jdbc:mysql://mysql:3306/vozsocial?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: vozsocial
    password: vozsocial123
    
  data:
    redis:
      host: redis
      port: 6379

storage:
  audio:
    base-path: /app/uploads/audio

logging:
  level:
    com.vozsocial: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
